name: Deploy to Host
on:
  workflow_dispatch:
    inputs:
      target_host:
        description: "Target Host (Flake Output)"
        required: true
        type: choice
        default: vm-app
        options:
          - cloud-observe
          - hypervisor
          - vm-app
          - vm-cyber
          - vm-monitor
          - vm-network
          - vm-public

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Resolve host IP address
        id: destination
        uses: ./.github/actions/resolve-host-ip
        with:
          host: ${{ inputs.target_host }}

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host-ip: ${{ steps.destination.outputs.ip }}

      - name: NixOS Rebuild & Switch
        run: |
          nix run github:nixos/nixpkgs/nixos-unstable#nixos-rebuild -- switch \
            --flake .#${{ inputs.target_host }} \
            --target-host root@${{ steps.destination.outputs.ip }} \
            --build-host root@${{ steps.destination.outputs.ip }} \
            --refresh \
            --option substituters "https://cache.ruijiang.me https://cache.nixos.org https://nix-community.cachix.org" \
            --option trusted-public-keys "cache.ruijiang.me-1:uSB517/xV6UnlCkzOYvmCSRG0sOqPPAGla5tY4iSQf0= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" \
            --show-trace
