name: Deploy to Host
on:
  workflow_dispatch:
    inputs:
      target_host:
        description: "Target Host (Flake Output)"
        required: true
        type: choice
        default: vm-app
        options:
          - cloud-observe
          - pi
          - hypervisor
          - vm-app
          - vm-cyber
          - vm-monitor
          - vm-network
          - vm-public

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ${{ inputs.target_host == 'pi' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Nix
        uses: ./.github/actions/install-nix
        with:
          github-token: ${{ github.token }}

      - name: Resolve host IP address
        id: destination
        uses: ./.github/actions/resolve-host-ip
        with:
          host: ${{ inputs.target_host }}

      - name: Install and Connect WireGuard
        uses: ./.github/actions/connect-wireguard
        with:
          config: ${{ secrets.WG_CONF }}

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host-ip: ${{ steps.destination.outputs.ip }}

      - name: NixOS Rebuild & Switch
        env:
          NIX_SSHOPTS: "-o StrictHostKeyChecking=no"
        run: |
          nix run github:nixos/nixpkgs/nixos-unstable#nixos-rebuild -- switch \
            --flake .#${{ inputs.target_host }} \
            --target-host root@${{ steps.destination.outputs.ip }} \
            --show-trace
